name: continouseDeployment
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: use Node v16
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_STG_URL }}
          REACT_APP_IAMPORT_ID: ${{ secrets.REACT_APP_IAMPORT_ID }}
          REACT_APP_IAMPORT_REST_API_SECRET: ${{ secrets.REACT_APP_IAMPORT_REST_API_SECRET }}
          REACT_APP_IAMPORT_REST_API_KEY: ${{ secrets.REACT_APP_IAMPORT_REST_API_KEY }}
        run: yarn build

      - name: zip create 
        run: zip -qq -r ./build.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build.zip s3://front-deployment/staging/build.zip

      - name: Deploy
        run: aws deploy create-deployment
          --application-name frontContinouseDeployment
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name staging
          --s3-location bucket=front-deployment,key=staging/build.zip,bundleType=zip
